# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventario.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\x12\ninventario\"\x1f\n\x11SolicitudProducto\x12\n\n\x02id\x18\x01 \x01(\x05\"Q\n\rNuevoProducto\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x02\x12\r\n\x05stock\x18\x03 \x01(\x05\x12\x11\n\tcategoria\x18\x04 \x01(\t\"X\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\x11\n\tcategoria\x18\x05 \x01(\t\"K\n\x11\x43\x61talogoProductos\x12\r\n\x05total\x18\x01 \x01(\x05\x12\'\n\tproductos\x18\x02 \x03(\x0b\x32\x14.inventario.Producto\"V\n\x0c\x43onfirmacion\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12&\n\x08producto\x18\x03 \x01(\x0b\x32\x14.inventario.Producto\"\x10\n\x0eSolicitudVacia2\xb2\x02\n\nInventario\x12\x46\n\x0fObtenerProducto\x12\x1d.inventario.SolicitudProducto\x1a\x14.inventario.Producto\x12L\n\x0fListarProductos\x12\x1a.inventario.SolicitudVacia\x1a\x1d.inventario.CatalogoProductos\x12\x44\n\rCrearProducto\x12\x19.inventario.NuevoProducto\x1a\x18.inventario.Confirmacion\x12H\n\x12TransmitirCatalogo\x12\x1a.inventario.SolicitudVacia\x1a\x14.inventario.Producto0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLICITUDPRODUCTO']._serialized_start=32
  _globals['_SOLICITUDPRODUCTO']._serialized_end=63
  _globals['_NUEVOPRODUCTO']._serialized_start=65
  _globals['_NUEVOPRODUCTO']._serialized_end=146
  _globals['_PRODUCTO']._serialized_start=148
  _globals['_PRODUCTO']._serialized_end=236
  _globals['_CATALOGOPRODUCTOS']._serialized_start=238
  _globals['_CATALOGOPRODUCTOS']._serialized_end=313
  _globals['_CONFIRMACION']._serialized_start=315
  _globals['_CONFIRMACION']._serialized_end=401
  _globals['_SOLICITUDVACIA']._serialized_start=403
  _globals['_SOLICITUDVACIA']._serialized_end=419
  _globals['_INVENTARIO']._serialized_start=422
  _globals['_INVENTARIO']._serialized_end=728
# @@protoc_insertion_point(module_scope)
