# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class InventarioStub(object):
    """------------------------------------------------------------
    SERVICIO  (define los métodos RPC disponibles)
    ------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerProducto = channel.unary_unary(
                '/inventario.Inventario/ObtenerProducto',
                request_serializer=inventario__pb2.SolicitudProducto.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.ListarProductos = channel.unary_unary(
                '/inventario.Inventario/ListarProductos',
                request_serializer=inventario__pb2.SolicitudVacia.SerializeToString,
                response_deserializer=inventario__pb2.CatalogoProductos.FromString,
                _registered_method=True)
        self.CrearProducto = channel.unary_unary(
                '/inventario.Inventario/CrearProducto',
                request_serializer=inventario__pb2.NuevoProducto.SerializeToString,
                response_deserializer=inventario__pb2.Confirmacion.FromString,
                _registered_method=True)
        self.TransmitirCatalogo = channel.unary_stream(
                '/inventario.Inventario/TransmitirCatalogo',
                request_serializer=inventario__pb2.SolicitudVacia.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)


class InventarioServicer(object):
    """------------------------------------------------------------
    SERVICIO  (define los métodos RPC disponibles)
    ------------------------------------------------------------

    """

    def ObtenerProducto(self, request, context):
        """Obtiene un producto por ID  (Unary RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarProductos(self, request, context):
        """Lista el catálogo completo   (Unary RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearProducto(self, request, context):
        """Registra un nuevo producto   (Unary RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransmitirCatalogo(self, request, context):
        """Transmite productos de uno en uno (Server-Side Streaming RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerProducto,
                    request_deserializer=inventario__pb2.SolicitudProducto.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=inventario__pb2.SolicitudVacia.FromString,
                    response_serializer=inventario__pb2.CatalogoProductos.SerializeToString,
            ),
            'CrearProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearProducto,
                    request_deserializer=inventario__pb2.NuevoProducto.FromString,
                    response_serializer=inventario__pb2.Confirmacion.SerializeToString,
            ),
            'TransmitirCatalogo': grpc.unary_stream_rpc_method_handler(
                    servicer.TransmitirCatalogo,
                    request_deserializer=inventario__pb2.SolicitudVacia.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventario.Inventario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventario.Inventario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventario(object):
    """------------------------------------------------------------
    SERVICIO  (define los métodos RPC disponibles)
    ------------------------------------------------------------

    """

    @staticmethod
    def ObtenerProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/ObtenerProducto',
            inventario__pb2.SolicitudProducto.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/ListarProductos',
            inventario__pb2.SolicitudVacia.SerializeToString,
            inventario__pb2.CatalogoProductos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/CrearProducto',
            inventario__pb2.NuevoProducto.SerializeToString,
            inventario__pb2.Confirmacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransmitirCatalogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inventario.Inventario/TransmitirCatalogo',
            inventario__pb2.SolicitudVacia.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
